### ISSUE TITLE
Stuff to fix

### ISSUE THREAD

**Issue by savnithyt** [savnithyt/frostedopmod#1]
Imposer system broken.
Admin system broken.
WorldEditBridge messed up a bit need to make sure it just stops the plugin if worldedit isn't present.
Admin commands.
New worlds loader.
On tab press complete name.
- more too add <3

Also /admin

**Comment by hitzzaf** [comment]
added admin commands:
/warn - Warn a player for an action. #6
/deop - Deop a player. #5 
/unloadchunks - Unload all unused chunks from the server. #7

**Comment by hitzzaf** [comment]
Fixed Imposter System: #9

**Comment by savnithyt** [comment]
Fixed erything :)
