### ISSUE TITLE
C_adminworld.java needs fixing

### ISSUE THREAD

**Issue by DeternoMC** [savnithyt/frostedopmod#21]
In the code, there is nothing that is detecting that the person doing the command is super, and there is no error message.

However, It might not be detecting if sender is a super if everyone is allowed in adminworld. But if that's the case, they can't do any commands besides /back, /spawn, /warp, /home, /tp. Either that or you block all access to world edit commands and block placement commands.

**Comment by Focusvity** [comment]
Are you an admin? If not, that's the correct behavior that Savnith implemented.
https://github.com/savnithyt/frostedopmod/blob/master/src/main/java/net/frostedop/frostedopmod/worlds/WorldManager.java#L31-L49

**Comment by savnithyt** [comment]
everything has been fixed
